[pytest]
asyncio_mode = auto
addopts = --strict-markers

# Specify directories to search for tests
testpaths = tests

# Set the minimum logging level
log_level = DEBUG

# Set the default fixture loop scope for pytest-asyncio
asyncio_default_fixture_loop_scope = function